# Generated by Django 4.1.3 on 2022-11-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mymodel1_caption_mymodel1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel1',
        ),
    ]
