# Generated by Django 4.1.3 on 2022-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_loadimage_image_alter_loadmultipleimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmultipleimages',
            name='image',
            field=models.FileField(upload_to='image'),
        ),
    ]
